(cd ../Crab.Head && dotnet build --no-dependencies)
(cd ../Crab && dotnet build --no-dependencies)
(cd ../Crab.Commands.Basics && dotnet build --no-dependencies)
(cd ../Crab.Commands.Botcontrol && dotnet build --no-dependencies)
(cd ../Crab.Commands.Fun && dotnet build --no-dependencies)
(cd ../Crab.Commands.Github && dotnet build --no-dependencies)
(cd ../Crab.Head && dotnet run)