(cd ../Crab && dotnet build)
(cd ../Crab.Commands && dotnet build)
(cd ../Crab.Commands.Botcontrol && dotnet build)
(cd ../Crab.Commands.Fun && dotnet build)
(cd ../Crab.Commands.Github && dotnet build)
(cd ../Crab.Head && dotnet run)